-- Insert sample smart gadgets data
INSERT INTO public.smart_gadgets (name, category, description, brand, price_usd, price_inr, availability_india, rating, image_url, product_url, tags, release_date) VALUES
('iPhone 15 Pro', 'Smartphones', 'Latest iPhone with titanium design and A17 Pro chip', 'Apple', 999, 83900, true, 4.8, 'https://example.com/iphone15.jpg', 'https://apple.com/iphone-15-pro', '{"smartphone", "iOS", "camera", "premium"}', '2023-09-22'),
('MacBook Air M2', 'Laptops', 'Ultra-thin laptop with M2 chip and all-day battery life', 'Apple', 1199, 99900, true, 4.7, 'https://example.com/macbook.jpg', 'https://apple.com/macbook-air', '{"laptop", "M2", "ultrabook", "productivity"}', '2022-07-15'),
('Samsung Galaxy S24 Ultra', 'Smartphones', 'Premium Android phone with S Pen and advanced camera system', 'Samsung', 1199, 99999, true, 4.6, 'https://example.com/galaxy.jpg', 'https://samsung.com/galaxy-s24', '{"smartphone", "android", "S-Pen", "camera"}', '2024-01-24'),
('iPad Pro 12.9"', 'Tablets', 'Professional tablet with M2 chip and Liquid Retina XDR display', 'Apple', 1099, 91900, true, 4.8, 'https://example.com/ipad.jpg', 'https://apple.com/ipad-pro', '{"tablet", "M2", "creative", "display"}', '2022-10-18'),
('Tesla Model Y', 'Electric Vehicles', 'All-electric SUV with autopilot and premium interior', 'Tesla', 52990, 4400000, false, 4.9, 'https://example.com/tesla.jpg', 'https://tesla.com/model-y', '{"EV", "SUV", "autopilot", "electric"}', '2020-03-15'),
('AirPods Pro 2', 'Audio', 'Premium wireless earbuds with active noise cancellation', 'Apple', 249, 20900, true, 4.5, 'https://example.com/airpods.jpg', 'https://apple.com/airpods-pro', '{"earbuds", "wireless", "ANC", "premium"}', '2022-09-23'),
('Sony WH-1000XM5', 'Audio', 'Industry-leading noise canceling headphones', 'Sony', 399, 33490, true, 4.6, 'https://example.com/sony.jpg', 'https://sony.com/headphones', '{"headphones", "ANC", "wireless", "premium"}', '2022-05-20'),
('Nothing Phone 2', 'Smartphones', 'Unique transparent design with Glyph interface', 'Nothing', 599, 44999, true, 4.3, 'https://example.com/nothing.jpg', 'https://nothing.tech/phone-2', '{"smartphone", "transparent", "unique", "glyph"}', '2023-07-11'),
('Steam Deck', 'Gaming', 'Portable gaming PC with SteamOS', 'Valve', 399, 33000, false, 4.4, 'https://example.com/steamdeck.jpg', 'https://steamdeck.com', '{"gaming", "portable", "PC", "steam"}', '2022-02-25'),
('Apple Watch Ultra 2', 'Wearables', 'Rugged smartwatch for extreme sports and adventures', 'Apple', 799, 66900, true, 4.7, 'https://example.com/watch.jpg', 'https://apple.com/watch-ultra', '{"smartwatch", "rugged", "sports", "health"}', '2023-09-22');

-- Insert sample tech news data
INSERT INTO public.tech_news (title, category, description, source, published_date, url, tags, image_url) VALUES
('Apple Unveils Vision Pro Mixed Reality Headset', 'Hardware', 'Apple introduces its first spatial computing device with revolutionary technology', 'TechCrunch', '2024-01-15 10:30:00+00', 'https://techcrunch.com/apple-vision-pro', '{"Apple", "VR", "Mixed Reality", "Spatial Computing"}', 'https://example.com/news1.jpg'),
('India Becomes Largest 5G Market Globally', 'Telecom', 'India surpasses China and US to become the worlds largest 5G subscriber base', 'Economic Times', '2024-01-14 08:45:00+00', 'https://economictimes.com/india-5g-market', '{"5G", "India", "Telecom", "Market Growth"}', 'https://example.com/news2.jpg'),
('OpenAI Launches GPT-4 Turbo with Enhanced Capabilities', 'AI/ML', 'New AI model offers improved reasoning and reduced costs for developers', 'The Verge', '2024-01-13 14:20:00+00', 'https://theverge.com/gpt-4-turbo', '{"OpenAI", "GPT-4", "AI", "Machine Learning"}', 'https://example.com/news3.jpg'),
('Indian Startups Raise $8.8 Billion in 2023', 'Startups', 'Despite global slowdown, Indian startup ecosystem shows resilience', 'Mint', '2024-01-12 11:15:00+00', 'https://mint.com/startup-funding-2023', '{"Startups", "Funding", "India", "Venture Capital"}', 'https://example.com/news4.jpg'),
('Google Bard Gets Real-Time Internet Access', 'AI/ML', 'Googles AI chatbot can now browse the web for up-to-date information', 'Android Authority', '2024-01-11 16:30:00+00', 'https://androidauthority.com/google-bard-internet', '{"Google", "Bard", "AI", "Internet Access"}', 'https://example.com/news5.jpg'),
('Tesla Cybertruck Deliveries Begin in India', 'Electric Vehicles', 'First batch of Cybertrucks arrive at Tesla service centers across major cities', 'AutoCar India', '2024-01-10 09:00:00+00', 'https://autocar.com/tesla-cybertruck-india', '{"Tesla", "Cybertruck", "Electric Vehicle", "India"}', 'https://example.com/news6.jpg'),
('Microsoft Copilot Integration Expands to Mobile Apps', 'Software', 'AI assistant now available across Word, Excel, and PowerPoint mobile versions', 'Tech Mahindra', '2024-01-09 13:45:00+00', 'https://techmahindra.com/microsoft-copilot-mobile', '{"Microsoft", "Copilot", "AI Assistant", "Mobile"}', 'https://example.com/news7.jpg'),
('Jio Launches 6G Research Center in Bangalore', 'Telecom', 'Reliance Jio invests ₹5000 crore in next-generation wireless technology research', 'Business Standard', '2024-01-08 07:30:00+00', 'https://business-standard.com/jio-6g-research', '{"Jio", "6G", "Research", "Bangalore"}', 'https://example.com/news8.jpg'),
('WhatsApp Introduces AI-Powered Business Tools', 'Social Media', 'Meta rolls out AI features for WhatsApp Business to help Indian SMEs', 'NDTV Tech', '2024-01-07 12:00:00+00', 'https://ndtv.com/whatsapp-ai-business', '{"WhatsApp", "AI", "Business Tools", "SME"}', 'https://example.com/news9.jpg'),
('Samsung Galaxy S24 Series Launched in India', 'Hardware', 'New flagship smartphones feature advanced AI capabilities and improved cameras', 'GSMArena', '2024-01-06 10:15:00+00', 'https://gsmarena.com/samsung-galaxy-s24-india', '{"Samsung", "Galaxy S24", "Smartphone", "AI Features"}', 'https://example.com/news10.jpg');