// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzgbkswhgyfhvhtzysuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Z2Jrc3doZ3lmaHZodHp5c3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTQ2ODQsImV4cCI6MjA2NzQ5MDY4NH0.rRD0KAOH5zHBrXB8N8lto21MkFU951seB6R_FhgV1ek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});